### ISSUE TITLE
NullReferenceException in Version.GetHashCode()

### ISSUE THREAD

**Issue by mbargiel** [adamreeve/semver.net#12]
Version.GetHashCode() throws a NullReferenceException when there is no PreRelease value set, which would be the case for most official release versions, e.g. "1.0.0". This prevents reliably using the Version class as a key in Dictionaries, despite an otherwise perfect implementation for this usage. (EDIT: That is, unless its string representation is used by calling .ToString().)

The culprit appears to be: https://github.com/adamreeve/semver.net/blob/master/SemVer/Version.cs#L180

**Comment by adamreeve** [comment]
Thanks for reporting this, it's fixed now.

**Comment by mbargiel** [comment]
Super quick response - kudos :)
