### ISSUE TITLE
Any chance you could change the license to apache or MIT?

### ISSUE THREAD

**Issue by niemyjski** [adamreeve/semver.net#14]
Not that credit isn't due but with your license anyone using your nuget package also has to copy your license file to their bin directory to be legal....
https://github.com/github/choosealicense.com/issues/257

**Comment by adamreeve** [comment]
Sorry for the delayed reply, yeah I'm happy to change the license to MIT to simplify things for people wanting to use this. I see @lvermeulen has +1d this, so I assume you're happy for your changes to be released under the MIT license after they're merged. @dennisroche, do you give permission for your changes to be released under the MIT license?

**Comment by dennisroche** [comment]
@adamreeve, yes absolutely. all contributes I make are under MIT.
