### ISSUE TITLE
1.0 release

### ISSUE THREAD

**Issue by felixfbecker** [adamreeve/semver.net#33]
A semver package should follow semver :)

> How do I know when to release 1.0.0?
>
> If your software is being used in production, it should probably already be 1.0.0. If you have a stable API on which users have come to depend, you should be 1.0.0. If you’re worrying a lot about backwards compatibility, you should probably already be 1.0.0.

http://semver.org/#how-do-i-know-when-to-release-100

**Comment by adamreeve** [comment]
:+1: you're right of course, 1.0 gives a sense of something finished, but people are depending on the API so it should definitely be 1.0 by now. I'll create a new 1.0 release and make sure I follow semver for future releases :)

**Comment by adamreeve** [comment]
I've released 1.0.0 to NuGet now :)
