### ISSUE TITLE
Align assembly and namespace name with Nuget package name

### ISSUE THREAD

**Issue by brphelps** [adamreeve/semver.net#46]
We have a project that ends up using an aggregate of packages from different areas, and one thing that we've run into problems with is that this package has overlapping assembly names / namespace names with a different package (SemVer) whose name aligns with their Nuget package name. 

I don't mind helping to make this change (also probably would be at least a minor version tick), but it would help us to isolate dependencies better while continuing to use this package.

**Comment by adamreeve** [comment]
Hi, yeah this is obviously not ideal but it would be a breaking change to fix it so would definitely require a major version increment. I think it does make sense to rectify this though so I'd be happy to accept a PR with a version bump to 2.0.0 if you're still interested.

**Comment by brphelps** [comment]
Alright, cool! I work with a small group of people on something consuming the library, I'm hopeful will get some time in the near future to pick the work up. Thanks for following up!

**Comment by adamreeve** [comment]
I've made this change on master now. I want to implement #49 before releasing 2.0.0 though so that I can do that in a binary incompatible way.
