### ISSUE TITLE
Error on range intersections (some intersections are non-commutative)

### ISSUE THREAD

**Issue by froggydood** [adamreeve/semver.net#52]
If I have 2 version ranges:
`range1 = new Range(">=1.0.0 <2.0.0")`
`range2 = new Range(">1.0.0")`

`range1.Intersect(range2) == ">=1.0.0 <2.0.0"`
`range2.Intersect(range1) == ">1.0.0 <2.0.0"`

The correct answer should be `">1.0.0 <2.0.0"`

**Comment by adamreeve** [comment]
Hi, thanks for the bug report, I'll look into fixing this.

**Comment by adamreeve** [comment]
The fix has been released in version 2.0.2.
