### ISSUE TITLE
Versions pefixed with v are parsed even in strict mode

### ISSUE THREAD

**Issue by anatawa12** [adamreeve/semver.net#57]
[Is “v1.2.3” a semantic version?](https://semver.org/#is-v123-a-semantic-version)
> No, “v1.2.3” is not a semantic version.

I think it should not parsed in strict mode.

https://dotnetfiddle.net/QtKY6r

**Comment by adamreeve** [comment]
Hi, yes you're right this probably should not have been allowed in strict mode. This library generally aims to be compatible with the node semver package, which allows a leading "v", but that also allows a leading "=" which we only allow in loose mode, so our behaviour is already a bit different. I think it makes sense to include this in the next major version release.
