### ISSUE TITLE
remove trimming version name?

### ISSUE THREAD

**Issue by anatawa12** [adamreeve/semver.net#60]
Currently `Version.Parse` accepts `" 1.0.1 "` but I think it should not.

**Comment by adamreeve** [comment]
Not sure about this one, does this create a problem for you? Spaces around a version in a dotnet package reference in a .csproj file are ignored for example, and being too strict could cause issues for some users. If you want extra strict checking you could test something like `version.Clean() == version.ToString()`

**Comment by anatawa12** [comment]
Sorry for late respond. I overlooked your response in inbox.

In semver spec, leading/trailing whitespaces are not accepted in regex on FQA. I think handling leading/trailing whitespaces is not responsibility of semver parser, a responsibility of application.

In semver parser in other languages, whitespaces are not likely to be ignored so when I make C# port of sone semver-based tool, I think it's likely for my tool to unexpectedly accepts whitespaces. (especially it's not documented on the Parse method)

If I want to allow leading/trailing whitespace, I can use `Version.Parse(string.Trim())`, which is more easy to know that allows leading/trailing whitespaces.

**Comment by adamreeve** [comment]
Right okay that makes sense. This could be a breaking change for some users though, and is definitely not just a chore as your PR title says! I think it's reasonable to include this in 3.0 too then.
