### ISSUE TITLE
No lazy-evaluation of ComparatorSet

### ISSUE THREAD

**Issue by mbargiel** [adamreeve/semver.net#7]
In the Range class constructor, using Linq to initialize the _comparatorSets field makes the field lazy-evaluated. This is the source of issues I'm running into (minor, I agree, but easily fixable):
1. It's not possible to detect that a rangeSpec is invalid until try to invoke one of the satisfaction methods/properties, which makes it impractical in a console-based app (e.g. you want to validate user input and give a meaningful error message before performing the command and failing in the middle due to an invalid user-provided range-spec).
2. Performing multiple calls to satisfaction methods/properties will recreate the ComparatorSet instances every time.

I suggest to make the _comparatorSets an array. This could be done by adding .ToArray() at the end (and change the field type). It would fix both issues: forcing the construction of the ComparatorSets immediately (throwing an exception on an invalid rangeSpec), and avoiding the instanciation of the ComparatorSets on every call to a satisfaction method/property.

**Comment by adamreeve** [comment]
Thanks for reporting this, it should be fixed now.
