### ISSUE TITLE
Include DataContract / DataMember annotations to make it serializable

### ISSUE THREAD

**Issue by xaviergonz** [adamreeve/semver.net#9]
Nice lib you got there. It would be awesome if it included DataContract / DataMember annotations to be able to serialize it to JSON, ProtoBuf, XML, etc. Or even better probably, a custom data serialization that serializes to/from the clean string.

Also for this to work properly it would require to have a protected parameterless constructor, something like:

protected Version()  : this("1.0.0") {
}

**Comment by lvermeulen** [comment]
@xaviergonz @adamreeve Please take into account that adding [DataContract] et al. will prohibit compatibility with .NET Core 1.0 RTM

**Comment by adamreeve** [comment]
Yeah it looks like there's no easy way to provide serialisation support built in to the library that will work with all platforms so I'll close this. I've also closed #13.
